USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/pantech/pororo/BoardConfigVendor.mk

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_CUSTOM_GRAPHICS:= ../../../device/pantech/pororo/graphics.c
TARGET_RECOVERY_INITRC = device/pantech/pororo/init.qcom.rc

TARGET_NO_BOOTLOADER := true

TARGET_BOOTLOADER_BOARD_NAME := pororo

BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=qcom loglevel=0
BOARD_KERNEL_RECOVERY_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=qcom loglevel=0
BOARD_KERNEL_BASE := 0x40200000
BOARD_PAGE_SIZE := 2048

BOARD_FORCE_RAMDISK_ADDRESS := 0x41300000
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 10485760
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 629145600
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1073741824

TARGET_PREBUILT_KERNEL := device/pantech/pororo/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_USES_MMCUTILS := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_USES_RECOVERY_CHARGEMODE := false
BOARD_SDCARD_DEVICE_PRIMARY := /dev/block/mmcblk1p1
BOARD_SDCARD_DEVICE_SECONDARY := /dev/block/mmcblk1
BOARD_SDEXT_DEVICE := /dev/block/mmcblk1p2
BOARD_HAS_LARGE_FILESYSTEM := true


